### PR TITLE
Fix SampleNode

### PR DESCRIPTION
**Pull request by lorenzhs**
This one should actually compute a random sample without replacement :)

Maybe it would be nice to have sampling *with* replacement in the future.  This should be possible fairly easily by modifying the PreOp, the assignment scheme distribution (binomial instead of hypergeometric), and the PostOp sampler.

### CODE REVIEW

**Comment by lorenzhs** [comment]
Manually merged into https://github.com/bingmann/thrill/commit/76ebe7f20e2b1ce0eac46e874b3515a36acec372

**Comment by bingmann** [comment]
Github notices once it's merged into the master repo

**Comment by lorenzhs** [comment]
I'm aware…

**Comment by bingmann** [comment]
tests still broken:
```
44: [ RUN      ] Operations.Sample
44: api_operations_test: /home/travis/build/bingmann/thrill/thrill/common/stats_timer.hpp:82: thrill::common::StatsTimerBase<true>& thrill::common::StatsTimerBase<true>::Start(): Assertion `!running_' failed.
 44/101 Test  #44: api_operations_test ....................................***Exception: Other 28.73 sec
```

**Comment by lorenzhs** [comment]
this was fixed and merged manually sometime in December or so. Closing.

**Pull request closed without merging**
