### PR TITLE
Collective Comm Improvements

### PR DESCRIPTION
**Pull request by emiswelt**
Changed sharing paradigm to use separate sharing segment for each worker. 
Use aligned pointer so store shared memory locations. 
Remove unnecessary barriers (From 4 to 2).

### CODE REVIEW

**Comment by bingmann** [comment]
Is there some isolated benchmark to check the improvement?

**Comment by emiswelt** [comment]
I've scheduled some benchmarks for tonight. In between, I kindly ask for a code review.

**Comment by emiswelt** [comment]
FYI: I've missed some of the recent changes on the cluster scripts - my benchmarks from yesterday are useless. We'll do again.

**Comment by emiswelt** [comment]
Thank you.

**Pull request merged**
