### PR TITLE
Mixed channel

### PR DESCRIPTION
**Pull request by toebbel**
this is not my work. But I create the PR for a better basis for discussions.

<DO NOT MERGE>

### CODE REVIEW

**Comment by toebbel** [comment]
I think there is too mych copy-paste-change-a-few-lines in this change.
Context::GetNewChannel --> duplicate
data::Channel --> three classes / files
ChannelPtr -> ConcatChannelPtr / MixChannelPtr
ChannelSet -> ConcatChannelSet / MixChannelSet
OpenConcatReader + OpenMixedReader
....

I think the better idea would be to use the ConcatReader (renamed to OrderedChannelReader) and UnorderedReader which both are attached to the Channel via a Callback interface. The Channel calls the callback with (BlockPtr, sender id) tuples. The Reader can put the stuff either into the correct order or not. Maybe this logic can be put into a BlockSource ?

By this we would have only one new class (the new block source type) and one additional method on the existing Channel class plus the callback interface.
The nice thing would be that the Callback Interface might be implemented in the future anyway since it allows operations to comsume blocks directly without any queue in between.

The whole data sub-system has way too many classes and becomes harder to maintain with every new class or concept :-1:


About the names - I would pledge to "Stream" since channel sounds more long-living (like the FlowControlChannels). And as described above I would leave it with one DataStream class and offer these methods: OpenOrderedReader & OpenUnorderedReader & OpenReaders

**Comment by bingmann** [comment]
Okay, let's see.

The problem is that the MixedQueue is *not* a BlockSource. It is actually a (from,Block)-PairSource, in some sense. And this queue is pivotal for the remaining design. The MixedReader must in the end wait on only one concurrent queue, and this is it. One cannot wait on multiple concurrent queues without a busy waiting loop.

How to actually deserialize items?, well this is done in the MixedReader by splitting up the streams from each source again. This is ugly but actually fixes all use cases (consume, reread, long block sequences, etc) by reusing BlockQueue. The thing is these split up streams need not be concurrent queues any more, simple ones suffice, but that is the only real ugly.

Hence, when receiving Blocks via the OnChannelBlock (this is the callback you're talking about), the Channel must put them into the right concurrent queue. For the ConcatChannel there are the p separate queues, for the MixedChannel there is the one (from,Block)-Queue. This is why there are two separate classes. And as you yourself noted a long time ago, the Multiplexer must know which kind of Channel it is receiving before the user calls the CreateChannel (-> hence the MagicByte).

So, while one could combine everything into one Channel class, it would have to contain both central concurrent queues: the vector<BlockQueue> for concat and the MixedBlockQueue for mixed. And one would be unused. I don't see a way around this (unless one does busy waiting on the vector<BlockQueue>). Hence, the API user decides which kind of queue by using the right class.

Stream... CatStream and MixStream? UnorderedStream is soo long.

**Comment by toebbel** [comment]
So, let's have the MixedBlockQueue have a different interface then, ok. 

But I would rather have some unused queue instances than so many classes.
We coul introduce the concept of a MultiQueue, that is internally either an array of queues or one single MixedBlockQueue. You append items by passing (blockPtr, sender). We pass the correct version of MixedBlockQueue as a template parameter into the Channel. The multiplexer does not need to know the actual difference of the concrete implementation of the classes.

**Comment by bingmann** [comment]
Hmm. I think what you are talking about may actually be easier to do:
Add pure virtual functions to the ChannelBase (rename to Channel).
That is what the MultiQueue in your proposal actually is: the distinction into the two Channel classes.
The methods of the channel then fail when requesting a Reader that does not work.

**Comment by bingmann** [comment]
Well, I renamed ChannelBase -> Channel and gave it common methods.
But I'm no really in favor of making virtual functions in Channel (OpenConcatReader) which can fail at runtime. That is what type checking is supposed to do. Which means that only ConcatChannel has these methods.

**Comment by bingmann** [comment]
`data::Channel` is renamed to `data::Stream`. I think it is a good name choice.
MixStream was not added to any DOpNode. This should be tested by the DOp authors with large data.

**Pull request merged**
