### PR TITLE
Api bench

### PR DESCRIPTION
**Pull request by sebalamm**

### CODE REVIEW

**Comment by bingmann** [comment]
You committed a 40 MB file, this commit must be deleted!

**Comment by bingmann** [comment]
Don't remove the file, remove the **commit** itself. We dont want a 40MB history.

**Comment by sebalamm** [comment]
Why not https://help.github.com/articles/removing-files-from-a-repository-s-history/ <https://help.github.com/articles/removing-files-from-a-repository-s-history/> ?

**Comment by bingmann** [comment]
There are many way. Remove the commit or file from history.

**Comment by bingmann** [comment]
This is a complete mess.

**Pull request closed without merging**
