### PR TITLE
WIP: Add logistic regression example

### PR DESCRIPTION
**Pull request by lorenzhs**
Based on [the easyLamda logistic regression example](https://github.com/haptork/easyLambda/blob/f17dde21f607bb973cab80c4a5fef74bec39fbf4/examples/logreg.cpp) by @haptork

### CODE REVIEW

**Comment by haptork** [comment]
The code looks neat. Thanks for the additions like `std::inner_product` that I ignored. Now that I am beginning to understand thrill, I've things that I really appreciate and things that I don't understand or have questions about. I will discuss them separately.

**Comment by lorenzhs** [comment]
Thanks. I particularly like `std::valarray`, which I only found out about yesterday. Its only drawback (as far as I can see) is that it doesn't work well with type deduction (`auto`), for some reason if I do
```c++
double foo(const std::valarray<double> &arr) {
    auto squared = arr * arr;
    return squared.sum();
}
```
...then `auto squared` is resolved to `std::valarray<int>` (or some other integer type), so types have to specified explicitly. That's a bit annoying. And a shorter way to write inner products would be nice as well, `(a*b).sum()` isn't very efficient as it needs to construct the temporary. Ah well.

**Comment by haptork** [comment]
I also came across valarray and thought the syntactic sugar it offers is impressive. I thought why haven't I ever saw it before and a few searches landed me [here](http://stackoverflow.com/a/1602787/1583711) and to few more links.

Some even mention that it exists in the standard just because nobody took the time to remove it. I dropped the idea.

**Comment by lorenzhs** [comment]
Right, I figured that it was pretty much abandoned after the whole `auto` situation. Still, I think it's a neat concept and could use a good implementation. Specifically, if it was possible to express a sequence of operations that would be nested (like our [function stack](https://github.com/thrill/thrill/blob/master/thrill/api/function_stack.hpp)) and vectorized, it could be really neat. I guess it would be better to drop that last commit for now, though.

**Comment by lorenzhs** [comment]
Builds are failing because your cdash submission script fails for forks. It should just not do anything instead of failing.

**Comment by lorenzhs** [comment]
@bingmann your build is weird on mac: https://travis-ci.org/thrill/thrill/jobs/139210764#L171

**Comment by bingmann** [comment]
please rebase

**Comment by lorenzhs** [comment]
I already did that this morning. It's on top of master. Mac build broke because of tests getting stuck, not build failure.

**Comment by lorenzhs** [comment]
Travis passed, MSVC still acting up. Doesn't look like that's my fault though.

**Comment by lorenzhs** [comment]
So what's the status on this, @bingmann?

**Pull request closed without merging**
