### PR TITLE
[not ready] Add GroupBy-Node

### PR DESCRIPTION
**Pull request by chaupow**

### CODE REVIEW

**Comment by chaupow** [comment]
please do not review yet. just wanted to check travis.

**Comment by chaupow** [comment]
Travis passed. This PR is waiting for review.

When reviewing, this conversation might be useful:
https://github.com/thrill/thrill/pull/67#issuecomment-139740663

**Comment by lorenzhs** [comment]
This still contains GPL headers in the old commits, to be safe you probably need to fix those in an interactive rebase (`git rebase -i`). Otherwise the licensing issues would apply to the whole project at those particular commits.

Sorry, Timo, but this can't be done without rewriting history ;)

**Comment by bingmann** [comment]
Well, then you tell Chau how to do it.
This is still a branch, so np on rewriting.

**Comment by lorenzhs** [comment]
@bingmann Okay, but not via the comments function

**Comment by chaupow** [comment]
@lorenzhs thanks.
i used `git rebase -i` before, shall i just squash all commit between the first commit that adds gpl and the commit that removes it?

**Comment by lorenzhs** [comment]
It's probably better to manually apply the changes of the commit that removes the GPL stuff to the commits that added the files (`edit` in the interactive rebase), otherwise you'd lose a lot of history

**Pull request merged**
